### ISSUE TITLE
Configuration of tasmota plugin

### ISSUE THREAD

**Issue by hapklaar** [kantlivelong/OctoPrint-PSUControl-Tasmota#1]
Hi, couple of questions:

How should the tasmota address be entered? I have tried http://<ip-address> and just the IP address but both don't seem to do anything.

What does 'plug' do?

Is there any logging I can check?

**Comment by kantlivelong** [comment]
Just the IP or hostname, Plug is the index number for the outlet. If a single outlet then 1 should work. 

Be sure to select the plugin in PSUControl

**Comment by kantlivelong** [comment]
Oh whoops missed the log part.

octoprint.log should provide a good chunk of info. Check out https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/Troubleshooting#how-to-provide-logs for how to grab debug logs.

Let me know how you make out.

**Comment by ssendev** [comment]
I had the same question so maybe changing the label to `IP Address / hostname` would help. 

I "think" i entered the ip first and it didn't work then tried with http then looked at the source and entered the ip again and then it worked. unfortunately i'm not sure what i did wrong the first time maybe i had an extra character somewhere from copying it.

either way it's working now so thanks for this plugin.

**Comment by kantlivelong** [comment]
I'll add a placeholder to the input.

**Comment by hapklaar** [comment]
Thanks for answering. I found out why I wasn't able to connect. It seems I'm not able to ping (or connect otherwise) my tasmota devices from other WIFI devices. They are only reachable from wired connected devices, must be some weird isolation setting in my Unifi setup I can't find...

**Comment by kantlivelong** [comment]
Addressed via 9de85029e146398207b391531aaab040c9a30567
